import os
excel_path=r"\\tvli-erib0703.ca.sbrf.ru\awrs\import_excel"
excel_name=[n for n in os.listdir(excel_path) if '.xlsx' in n]
debug=False
mapping={"active_logapp":"LogApp",
"nt1_atm":"PhizATM",
"nt1_eribrouter_lin":"EribRouter",
"nt1_eribrouter":"EribRouter",
"nt1_mapi":"PhiziC (MAPI)",
"nt1_pcidss":"PCI_DSS",
"nt1_pfm":"PhizPFM",
"nt1_scheduler":"PhizScheduler",
"nt1_web":"PhiziC (WEB)",
"nt1_900":"900",
"nt2_active_logapp":"LogApp",
"nt2_atm":"PhizATM",
"nt2_codevent":"CodEventListener",
"nt2_confirmdoc_lin":"ConfirmDocApp",
"nt2_eribrouter":"EribRouter",
"nt2_gatecod":"PhizGateCOD",
"nt2_iqwave":"PhizGateIQWave",
"nt2_logapp":"LogApp",
"nt2_mapi":"PhiziC (MAPI)",
"nt2_mapi_new":"PhiziC (MAPI Linux)",
"nt2_omni":"OmniChannelHistoryGatewayApp",
"nt2_pcidss":"pci.dss",
"pcidss_node":"pci.dss",
"nt2_prior":"PriorityCardApp",
"nt2_pfm":"PhizPFM",
"nt2_sberid":"PhizSberID",
"eribrouter_lin":"ERIBRouter",
"nt2_scheduler":"PhizScheduler",
"nt2_usct":"USCTApp",
"nt2_web":"PhiziC (WEB)",
"nt2_web_new":"PhiziC (WEB Linux)",
"nt2_wsgate":"WSGateListener",
"nt3_mapi":"PhiziC (MAPI)",
"nt3_scheduler":"PhizScheduler",
"nt3_web":"PhiziC (WEB)",
"nt3_omni":"OmniChannelHistoryGatewayApp"}