stend='NT1'
group='NT1'
scenario_id='252'
branchLTScripts='master'
branchDatapools='master'
scheduler='L'
profile_percentage='100'
target_comment='НТ1 надежность'
test_time=True
influx_drop=True
skip_pending=True
disable_transactions=True
M_TEST=''
jira_comment=''
user='khudyakov1-ad'
wait_shd=False
properties_scheduler=''